---
driver:
  name: <%= ENV['KITCHEN_DRIVER'] || 'vagrant' %>

provisioner:
  name: chef_zero

platforms:
  - name: centos-7.2
  - name: debian-8.2
  - name: fedora-23
  - name: ubuntu-14.04

# For testing joining the domain, see .kitchen.local.yml.EXAMPLE
suites:
  - name: default
    run_list:
      - recipe[realmd-sssd]
      - recipe[test-helper::serverspec]
